pre-commit:
  commands:
    black:
      files: git ls-files
      glob: '*.{py, ipynb}'
      run: black {staged_files}
      stage_fixed: true
    clean-jupyter:
      files: git ls-files
      glob: '*.ipynb'
      run: jupyter nbconvert --clear-output --inplace {staged_files}
      stage_fixed: true
